# Use Node 18 as the base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 1337
EXPOSE 1337

# Start Strapi
CMD ["npm", "run", "develop"]